language: node_js
node_js:
- '0.12'
branches:
  only:
  - blog
before_install: 
install:
- npm install -g hexo
- npm install
before_script:
- git config --global user.name 'Steve ZHANG'
- git config --global user.email 'stevzhg@gmail.com'
script:
- hexo generate
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init
  && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
dd:
- openssl aes-256-cbc -K $encrypted_a33f091765f3_key -iv $encrypted_a33f091765f3_iv
  -in id_rsa.enc -out id_rsa -d
