language: node_js

node_js:
- '0.12'

branches:
  only:
  - blog

before_install: 
- openssl aes-256-cbc -K $encrypted_a33f091765f3_key -iv $encrypted_a33f091765f3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "Steve ZHANG"
- git config --global user.email stevzhg@gmail.com
- git clone -b blog git@github.com:v2cc/v2cc.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- hexo d